-- MySQL Script generated by MySQL Workbench
-- Tue Nov 20 17:10:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

drop database if exists pdf_chato;

-- -----------------------------------------------------
-- Schema pdf_chato
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pdf_chato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pdf_chato` DEFAULT CHARACTER SET utf8 ;
USE `pdf_chato` ;

-- -----------------------------------------------------
-- Table `pdf_chato`.`entities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdf_chato`.`entities` (
  `entity_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`entity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdf_chato`.`contexts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdf_chato`.`contexts` (
  `context_id` INT NOT NULL AUTO_INCREMENT,
  `text` MEDIUMTEXT NOT NULL,
  `capitulo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`context_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdf_chato`.`entities_contexts_rel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdf_chato`.`entities_contexts_rel` (
  `entity_id` INT NOT NULL,
  `context_id` INT NOT NULL,
  PRIMARY KEY (`entity_id`, `context_id`),
  INDEX `context_id_idx` (`context_id` ASC),
  CONSTRAINT `entity_id`
    FOREIGN KEY (`entity_id`)
    REFERENCES `pdf_chato`.`entities` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `context_id`
    FOREIGN KEY (`context_id`)
    REFERENCES `pdf_chato`.`contexts` (`context_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
